# Este workflow realiza las siguientes tareas:
# 1. Compila el proyecto Java usando Gradle
# 2. Ejecuta todos los tests unitarios
# 3. Ejecuta los tests de comportamiento con Cucumber
# 4. Archiva los resultados de los tests y los artefactos compilados
# 5. Se ejecuta en cada push a main y en pull requests

name: Build and Test PMTool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Build and test with Gradle
        run: ./gradlew build

      - name: Execute Cucumber tests
        run: ./gradlew cucumber

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/build/reports/tests/
            **/build/test-results/
            **/build/reports/cucumber/

      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/build/libs/
            **/build/distributions/

      - name: Archive Checkstyle results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-results
          path: |
            **/build/reports/checkstyle/
