# Este workflow realiza las siguientes tareas:
# 1. Compila el proyecto Java usando Gradle
# 2. Ejecuta todos los tests unitarios
# 3. Archiva los resultados de los tests y los artefactos compilados
# 4. Se ejecuta en cada push a main y en pull requests

name: Build and Test PMTool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew build

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/tests/test

      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: app/build/libs
